/*
  Warnings:

  - The values [COMPLETED] on the enum `TRANSFER_REQUEST_STATUS` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "TRANSFER_REQUEST_STATUS_new" AS ENUM ('PENDING', 'FULFILLED', 'REJECTED');
ALTER TABLE "TransferRequests" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "TransferRequests" ALTER COLUMN "status" TYPE "TRANSFER_REQUEST_STATUS_new" USING ("status"::text::"TRANSFER_REQUEST_STATUS_new");
ALTER TYPE "TRANSFER_REQUEST_STATUS" RENAME TO "TRANSFER_REQUEST_STATUS_old";
ALTER TYPE "TRANSFER_REQUEST_STATUS_new" RENAME TO "TRANSFER_REQUEST_STATUS";
DROP TYPE "TRANSFER_REQUEST_STATUS_old";
ALTER TABLE "TransferRequests" ALTER COLUMN "status" SET DEFAULT 'PENDING';
COMMIT;
