name: Deploy API

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Server
        run: npm run build

      - name: Upload to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "backend/dist/*"
          target: /var/www/blackbridge/
          rm: true

      - name: Restart pm2 on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script_path: .github/scripts/redeploy.sh

      # - name: Run deployment script on EC2
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ec2-user
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     script: |
      #       cd /home/ec2-user
      #       ./start.sh
